web-ui/src/main/resources/catalog/components/common/map/partials/drawbbox.html, web-ui/src/main/resources/catalog/components/utility/UtilityDirective.js, web-ui/src/main/resources/catalog/components/utility/partials/regionpicker.html, web-ui/src/main/resources/catalog/style/gn.less, web-ui/src/main/resources/catalog/views/default/less/gn_editor_default.less
- re-order the UI element
- group elements (add elements to a toolbar for the map)
- change delete icons and couple them to the input fields
- delete the previous search item when switching the region type
Backport of #4975
=> [BP] UI improvements for the bounding box block in the editor:

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/components/search/map/MapFieldDirective.js, web-ui/src/main/resources/catalog/views/default/less/gn_map_default.less, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/AdvSearchForm.html
Add a search map in the advanced search form
Related to _GeoCat#909992 - Advanced search - add a search by bounding box function with a map_.
=> Search map in advanced search form

core/src/main/java/jeeves/server/UserSession.java, core/src/main/java/org/fao/geonet/kernel/SchemaManager.java, core/src/main/java/org/fao/geonet/kernel/batchedit/CSVBatchEdit.java, core/src/main/java/org/fao/geonet/kernel/batchedit/CustomElement.java, core/src/main/java/org/fao/geonet/kernel/batchedit/DateEditElement.java, core/src/main/java/org/fao/geonet/kernel/batchedit/KeywordEditElement.java, core/src/main/java/org/fao/geonet/kernel/batchedit/OnlineResourceEditElement.java, core/src/main/java/org/fao/geonet/kernel/datamanager/base/BaseMetadataManager.java, core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserConfiguration.java, core/src/main/java/org/fao/geonet/kernel/security/shibboleth/ShibbolethUserUtils.java, schemas/iso19115-3/src/main/plugin/iso19115-3/csv/distribution-link.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/csv/keyword-thesaurus.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/csv/online-resource.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/csv/resource-format.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/process/owner-add.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/process/transform_internal_ind.xsl, services/src/main/java/org/fao/geonet/api/records/editing/BatchEditsApi.java, web-ui/src/main/resources/catalog/js/edit/BatchEditController.js, web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth-overrides.properties, web/src/main/webapp/WEB-INF/config-security/config-security-shibboleth.xml
- Add Owner to metadata for newly created record
- Update Shibboleth configuration to capture position and division and update the user
=> - Update CSV BatchUpload

schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-dataset.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-service.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-source.xml
- Add space between ClassificationSystem
- Add individual contact for Metadata
=> Fix https://gajira.atlassian.net/browse/ECAT-500

web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html
=> Fix https://gajira.atlassian.net/browse/ECAT-529

web-ui/src/main/resources/catalog/templates/editor/top-toolbar.html
- Disable ‘Save and Submit’
- https://gajira.atlassian.net/browse/ECAT-529?focusedCommentId=100962
=> Fix updated request on jira-ecat-529

web-ui/src/main/resources/catalog/locales/en-search.json
- Redirect unauthenticated users to shibboleth login for sso
=> Fix https://gajira.atlassian.net/browse/ECAT-525

schemas/iso19115-3/src/main/plugin/iso19115-3/formatter/datacite/view.xsl
- Add support for minting document DOIs
=> Fix https://gajira.atlassian.net/browse/ECAT-541

schemas/iso19115-3/src/main/plugin/iso19115-3/index-fields/common.xsl, services/src/main/java/org/fao/geonet/api/records/MetadataInsertDeleteApi.java, web-ui/src/main/resources/catalog/views/default/module.js, web-ui/src/main/resources/catalog/views/default/templates/recordView.html, web/src/main/webapp/WEB-INF/config-lucene.xml
Reverting commits until further verification to resolve https://gajira.atlassian.net/browse/ECAT-542
=> Ecat3.10 devtw jiraecat 542

schemas/iso19115-3/src/main/plugin/iso19115-3/index-fields/common.xsl, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-dataset.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-service.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-source.xml, web-ui/src/main/resources/catalog/views/default/templates/recordView.html, web/src/main/webapp/WEB-INF/config-lucene.xml
- update templates
- update common xsl
- update lucene index
- update front end form
=> Fix https://gajira.atlassian.net/browse/ECAT-511

schemas/iso19115-3/src/main/plugin/iso19115-3/index-fields/common.xsl, web-ui/src/main/resources/catalog/views/default/templates/AdvSearchForm.html
First item on: https://gajira.atlassian.net/browse/ECAT-552
- The ability to search for 'Point of Contact' role (as per the current Author search)
=> Advanced search point of contact

web-ui/src/main/resources/catalog/js/edit/EditorBoardController.js
- The ability to display any records that have a ‘working copy’
=> Fix https://gajira.atlassian.net/browse/ECAT-552

.travis.yml
- Include Test branch in Travis
=> Update travis with TEST

web-ui/src/main/resources/catalog/views/default/templates/about.html
=> ha-testing:  adding question mark

web-ui/src/main/resources/catalog/views/default/templates/about.html
Reverts ga-gn/core-geonetwork#85
=> Revert "ha-testing:  adding more question marks"

web-ui/src/main/resources/catalog/views/default/templates/about.html
Reverts ga-gn/core-geonetwork#84
=> Revert "ha-testing:  adding question mark"

schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-dataset.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-service.xml
Updating the copyright year from 2021 to 2022
=> Fix https://gajira.atlassian.net/browse/ECAT-569

web-ui/src/main/resources/catalog/locales/en-admin.json
UI changes for the DOI minting to use https:// links.
=> Fix for https://gajira.atlassian.net/browse/ECAT-575

web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/locales/en-admin.json
Merging ecat-dev to our master.
=> Fix for https://gajira.atlassian.net/browse/ECAT-575 

schemas/iso19115-3/src/main/plugin/iso19115-3/formatter/datacite/view.xsl
Adding collection scope type for minting DOIs.
=> Fix for https://gajira.atlassian.net/browse/ECAT-577

doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-dataset.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-service.xml
Merging ecat-dev to our master.
=> Fix for https://gajira.atlassian.net/browse/ECAT-612

schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-dataset.xml, schemas/iso19115-3/src/main/plugin/iso19115-3/templates/ga-19115-3-service.xml
=> Fix for https://gajira.atlassian.net/browse/ECAT-648

doi/src/main/java/org/fao/geonet/doi/client/DoiBuilder.java, doi/src/main/java/org/fao/geonet/doi/client/DoiManager.java, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/formatter/datacite/view.xsl, services/src/main/java/org/fao/geonet/api/records/DoiApi.java, web-ui/src/main/resources/catalog/components/common/alert/partials/alert.html, web-ui/src/main/resources/catalog/components/metadataactions/MetadataActionService.js, web-ui/src/main/resources/catalog/components/search/resultsview/partials/selection-widget.html, web-ui/src/main/resources/catalog/locales/en-core.json, web-ui/src/main/resources/catalog/views/default/directives/partials/mdactionmenu.html, web-ui/src/main/resources/catalog/views/default/less/gn_search_default.less
- Added Create/Update DOI button in search and editor view.
- Added message when creating DOI (failed, updated, created).
- Used eCatID.
- Added Scope Codes.
For details, pls. check the ECAT-654 ticket
=> Implemented https://gajira.atlassian.net/browse/ECAT-654

core/src/main/java/org/fao/geonet/constants/Geonet.java, schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/process/add-publication.xsl, services/src/main/java/org/fao/geonet/api/records/MetadataSharingApi.java
=> Implemented https://gajira.atlassian.net/browse/ECAT-667

schemas/iso19115-3.2018/src/main/plugin/iso19115-3.2018/set-gaid.xsl
This will remove the extra Acquisition Information XML issue.
=> Fix for https://gajira.atlassian.net/browse/ECAT-729

web-ui/src/main/resources/catalog/views/default/less/gn_result_default.less, web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
=> Fix for http://gajira.atlassian.net/browse/ECAT-747

web-ui/src/main/resources/catalog/views/default/less/gn_view.less, web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
Add left border and corner based on feedback from DGC team.
Please see comments in ticket ECAT-747
=> ECAT-747 add left border and radius to copy-to-clipboard button

web-ui/src/main/resources/catalog/views/default/templates/recordView/technical.html
=> Fix for https://gajira..atlassian.net/browse/ECAT-742 - remove underscore
